builds:
  -
    ldflags: -s -w -X github.com/bpineau/kube-deployments-notifier/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
    goarch:
      - amd64

before:
  hooks:
  - go mod download

#release:
#  # don't autopublish
#  draft: true

changelog:
  filters:
    exclude:
      - Merge

dockers:
  - image_templates:
    - "bpineau/kube-deployments-notifier:latest"
    - "bpineau/kube-deployments-notifier:{{ .Tag }}"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
